apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeehub-backend
  namespace: employeehub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employeehub-backend
  template:
    metadata:
      labels:
        app: employeehub-backend
    spec:
      containers:
        - name: backend
          image: ps73171/employeehub-backend:27
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://employeehub:EmployeeHub@123@employeehub-database:5432/employeehub"

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD

            - name: DB_HOST
              value: "employeehub-database"

            - name: DB_PORT
              value: "5432"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20