apiVersion: v1
kind: Service
metadata:
  name: employeehub-database
  namespace: employeehub
spec:
  selector:
    app: employeehub-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP