apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: employeehub
type: Opaque
stringData:
  POSTGRES_DB: employeehub
  POSTGRES_USER: employeehub
  POSTGRES_PASSWORD: EmployeeHub@123