apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: employeehub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client